package org.example.app/*
 * This source file was generated by the Gradle 'init' task
 */


//import org.apache.commons.text.WordUtils
import org.apache.commons.lang3.StringUtils // Use this one


import kotlin.text.split

fun main() {
    fun processMessage() {
        val message = MessageUtils.getMessage()
        val tokens = StringUtils.split(message) // Apache Commons Lang version
        val result = StringUtils.join(tokens)   // Apache Commons Lang version
        // println(WordUtils.capitalize(result))
        println(result)
//    val tokens = StringUtils.split(MessageUtils.getMessage())
//   val result = StringUtils.join(tokens)
//    println(WordUtils.capitalize(result))
}}
